apiVersion: v1
kind: Secret
metadata:
  name: planit-strategy-secret
  namespace: planit-dev

type: Opaque

stringData:
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: rootroot
  JWT_SECRET: planit-user-service-secret-key-change-in-production-please

  GNEWS_API_KEY: b701ae4d549a3e2a2d136c118333627d