apiVersion: v1
kind: Service

metadata:
  name: planit-strategy-svc
  namespace: planit-dev
  labels:
    app: strategy
    tier: backend
    env: dev

spec:
  type: ClusterIP

  selector:
    app: strategy

  ports:
    - name: http
      port: 8083
      targetPort: 8083

    - name: grpc
      port: 9093
      targetPort: 9093