apiVersion: v1
kind: ConfigMap
metadata:
  name: planit-user-config
  namespace: planit-dev

data:
  SERVER_PORT: "8081"

  SPRING_DATASOURCE_URL: "jdbc:mariadb://planit-dev-rds.cd06cqgoq2qg.ap-northeast-2.rds.amazonaws.com:3306/planit_user_db"

  REDIS_HOST: "planit-redis.gyo6nz.0001.apn2.cache.amazonaws.com"
  REDIS_PORT: "6379"

  AWS_REGION: "ap-northeast-2"

  GRPC_SERVER_PORT: "9091"

  JWT_ACCESS_TOKEN_VALIDITY: "900000"
  JWT_REFRESH_TOKEN_VALIDITY: "604800000"