apiVersion: apps/v1
kind: Deployment
metadata:
  name: planit-user-deploy
  namespace: planit-dev
  labels:
    app: user
    tier: backend
    env: dev

spec:
  replicas: 2

  selector:
    matchLabels:
      app: user

  template:
    metadata:
      labels:
        app: user
        tier: backend
        env: dev

    spec:
      containers:
        - name: user
          image: 746491138596.dkr.ecr.ap-northeast-2.amazonaws.com/planit-user:v3.3

          ports:
            - containerPort: 8081
            - containerPort: 9091

          envFrom:
            - configMapRef:
                name: planit-user-config
            - secretRef:
                name: planit-user-secret

          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          volumeMounts:
            - name: logs-volume
              mountPath: /app/logs

          startupProbe:
            httpGet:
              path: /api/v1/users/actuator/health
              port: 8081
            failureThreshold: 30
            periodSeconds: 5
            timeoutSeconds: 2

          readinessProbe:
            httpGet:
              path: /api/v1/users/actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 5

          livenessProbe:
            httpGet:
              path: /api/v1/users/actuator/health
              port: 8081
            initialDelaySeconds: 90
            periodSeconds: 15
            timeoutSeconds: 2
            failureThreshold: 5

      volumes:
        - name: logs-volume
          emptyDir: {}