apiVersion: v1
kind: Secret
metadata:
  name: planit-user-secret
  namespace: planit-dev

type: Opaque

stringData:
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: rootroot

  JWT_SECRET: planit-user-service-secret-key-change-in-production-please

  REDIS_PASSWORD: ""

  # Cognito
  COGNITO_USER_POOL_ID: "ap-northeast-2_GKpckavjT"
  COGNITO_CLIENT_ID: "6j5ajq8p3b7d894qt5msp4hair"